circabc_base_url: "https://circabc.europa.eu"

folders:

  - group_id: "a0b483a2-4c05-4058-addf-2a4de71b9a98"
    library_id: "84998de9-01ff-4434-b566-85367d2fae5b"
    name: "CARACAL"
    recursive: true

# CIRCABC pagination
items_per_page: 100

# Maximum number of pages per folder
max_pages: 50

request_timeout: 30
request_retries: 3
request_delay: 0.5

max_feed_items: 200

feed_url: "https://YOUR-USERNAME.github.io/YOUR-REPOSITORY/feed.xml"
